compiler:
  - clang
  - gcc
os: linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libpopt-dev botan1.10-dev libasio-dev libboost-system-dev libjsoncpp-dev
script: mkdir build && cd build && cmake ../src && make
language: cpp
notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.oftc.net#tor-dev"
    on_success: always
    on_failure: never
    skip_join: true
deploy:
  provider: script
  script: echo "HI"
  on:
    branch: master
